name: Run name test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      secret1: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo $secret1
      - run: echo "$secret1"
      - run: echo {{ secrets.GITHUB_TOKEN }}
      - run: echo "ğŸ This job's status is ${{ job.status }} !!!."

